### ISSUE TITLE
Pagination is disabled in `Git#versions_for_path`

### ISSUE THREAD

**Issue by jhominal** [gollum/rugged_adapter#10]
Hello,

I was wondering why, in [`Git#versions_for_path`](https://github.com/gollum/rugged_adapter/blob/v0.4.1/lib/rugged_adapter/git_layer_rugged.rb#L225), both `:max_count` and `:skip` are removed from the `options` hash:

```ruby
def versions_for_path(path = nil, ref = nil, options = {})
  options.delete :max_count
  options.delete :skip
  log(ref, path, options)
end
```

That leads to a big performance regression for me, as I have a very deep wiki history (the wiki was migrated).

The [corresponding function in Grit](https://github.com/gollum/grit_adapter/blob/v1.0.0/lib/grit_adapter/git_layer_grit.rb#L195) only disables pagination when the `:follow` option is enabled:

```ruby
def versions_for_path(path = nil, ref = nil, options = nil)
  if options[:follow]
    options[:pretty] = 'raw'
    options.delete :max_count
    options.delete :skip
    logstr = log(path, ref, options)
    Gollum::Git::Commit.list_from_string(repo, logstr)
  else
    repo.log(ref, path, options).map {|grit_commit| Gollum::Git::Commit.new(grit_commit)}
  end
end
```

**Comment by bartkamphorst** [comment]
Good question, especially since `#log` [does want to use them](https://github.com/gollum/rugged_adapter/blob/master/lib/rugged_adapter/git_layer_rugged.rb#L206-L207).

**Comment by dometto** [comment]
Thanks for reporting this, it looks like I messed up there. If you could follow @bartkamphorst's suggestion and see if it passes the gollum-lib specs (see the readme), we would welcome a PR!

**Comment by jhominal** [comment]
OK, I will do that.

I am currently running my instance with the Rugged adapter, version 4.0.1, with these lines commented out. So far, so good, so I will leave it that way and see if it breaks for anyone. (I have made very basic tests of things that should work).

I will run the gollum-lib specs later (not too familiar with Ruby) - if it does not work, I will comment here, otherwise I will make the PR.

**Comment by dometto** [comment]
Great, thanks in advance!

**Comment by bartkamphorst** [comment]
> So far, so good

Also meaning that you are seeing the expected behavior, in that the settings are now honored properly? Thanks for testing this out!
