### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by gerwitz** [gollum/rugged_adapter#14]
The recent PRs from @jhominal are helpful enough that I'd like to use them in production.

**Comment by bartkamphorst** [comment]
Ideally I would want a fix for #5 included. @dometto What are your thoughts on this?

**Comment by dometto** [comment]
I agree but have little time to work on #5...

**Comment by dometto** [comment]
I released 0.4.2 since it's now been a while. We'll try to fix #5 soon and release another update.

**Comment by gerwitz** [comment]
Thanks! I can finally clean up a bit of [rails-wiki](https://github.com/TheArtificial/rails-wiki) that's been annoying me.
