### ISSUE TITLE
Allow gollum wiki page names to be utf8-encoded in Gitlab

### ISSUE THREAD

**Issue by dansou901** [gollum/rugged_adapter#16]
Hi,
in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2999 it says that it's waiting for this to support rugged 0.24. Problem is, when creating wiki pages in Gitlab you can't use non ascii characters. That's bad for non english people. Can you have a look at this? Thanks!
Regards,
dansou901

**Comment by bartkamphorst** [comment]
@dansou901 This is a known issue (e.g., see [here](https://github.com/gollum/gollum/issues/1102) but also [here](https://github.com/gollum/rugged_adapter/issues/5)). As gollum is an open source project, feel free to propose / submit a solution and we will happily review it. Until then, we have no timeline for a fix and I'm closing this as a duplicate.

**Comment by brendanokane** [comment]
Does anyone know of any git-backed wikis for which this isn't an issue? I appreciate that gollum is open-source and that all the fine work that people have done on it has been on a volunteer basis and as a labor of love, but the inability to have pages named, e.g., "明清小說" is a deal-breaker for my use case.

**Comment by dometto** [comment]
Not that I personally know of, @brendanokane. I realise that this is an important issue though. I'd love to see it resolved, but could use any help with that. Even if someone could just write some specs for the required behavior, that would be great.
