### ISSUE TITLE
Where is code for 0.2b release?

### ISSUE THREAD

**Issue by buger** [gollum/rugged_adapter#4]
I see that rubygems contain 0.2b release, but this repo have only 0.1b. What i'm missing?

**Comment by bartkamphorst** [comment]
Excellent question, @buger. @dometto? :)

**Comment by dometto** [comment]
Something must have gone wrong when pushing the new tag. The code in master should be the 0.2b code though. I'll make sure later today.

**Comment by dometto** [comment]
Sorry about that @buger -- pushed the new version commit and tag just now.
