### ISSUE TITLE
Cannot load such file -- gollum-lib (LoadError)

### ISSUE THREAD

**Issue by jxm262** [gollum/rugged_adapter#6]
For the life of me, I can't figure this out (although I'm fairly new to Ruby).  

When I try to follow your instructions, I get this when I attempt to run 
```  
gollum --adapter rugged
>/mydir/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- gollum-lib (LoadError)  
```  
  
I've also tried installing gollum and the rugged_adapter from source with no luck.  Running mac on Yosemite

**Comment by dometto** [comment]
What's the output of `gem list gollum`?

**Comment by jxm262** [comment]
shows this ..
```
*** LOCAL GEMS ***

gollum (3.1.2)
gollum-grit_adapter (1.0.0, 0.1.3)
gollum-lib (4.0.2, 4.0.1)
gollum-rugged_adapter (0.2b)
```  

It actually looks like it may be a problem with my gollum installation.  I've tried removing/rebuilding with no luck.

**Comment by jxm262** [comment]
Ok, yeah I'm getting an error with gollum now.  I'll remove this ticket , sorry for jumping the gun and opening this so soon.  
Error now is 
`cannot load such file -- github/markup`
