### ISSUE TITLE
Please release 2.0.1, relaxing rugged dependency.

### ISSUE THREAD

**Issue by c4lliope** [gollum/rugged_adapter#61]
Gollum is unusable on Ruby 3.2 because Rugged 1.1 has a compilation error.
A couple simple releases are needed to keep the dependency chain building properly.

Please release a 2.0.1 upgrade based on `master`, as-is. This includes:
https://github.com/gollum/rugged_adapter/pull/56

Once this is done, `gollum-lib` needs a 5.x release (either 5.2.3 or 5.3)
making a change to the `gollum-rugged_adapter` dependency here:
https://github.com/gollum/gollum-lib/blob/master/gollum-lib.gemspec

Please help make the ruby 3.2 upgrade experience amazing for us all!

**Comment by c4lliope** [comment]
CC @dometto !!

**Comment by dometto** [comment]
Sorry for the slow response on this, I've had some downtime this month. I'm aware of the issue and I'll cut a new release sometime this week. Thanks for your patience!

**Comment by c4lliope** [comment]
All good; there's less of a rush.
I'd been hoping to use gollum for the wikitext support -
and I learned that wikicloth only runs on 2.7; see my research on:
https://github.com/requarks/wiki/discussions/6213

**Comment by mjsir911** [comment]
Yeah looking forward to the new release with libgit-1.5.0+ too!

**Comment by dometto** [comment]
`v2.1` has been released.
