### ISSUE TITLE
Searching generates false-positives

### ISSUE THREAD

**Issue by techwiz24** [gollum/rugged_adapter#7]
Searching for a keyword while using the rugged adapter sometimes generates false positives. For example, in a private wiki consisting of 150+ pages, searching for **citrix** returned the following results:

![](https://cloud.githubusercontent.com/assets/794251/7011248/8ba0ead8-dc75-11e4-9886-9923a9d76bc4.png)

Notice that the few results are uploaded screenshots and are included as expected. Due to a [file encoding issue](https://github.com/gollum/gollum/issues/934#issuecomment-90226780) in my environment, some of the expected results were NOT returned because the search term was not listed in the filename **exactly** as searched. For example, none of these pages were included in the search result:

![image](https://cloud.githubusercontent.com/assets/794251/7011810/4c428108-dc7a-11e4-8eae-f4c1a37ea4b4.png)

However, towards the end of the screenshot, you will notice that pages that do not mention the search term nor contain the search term in their name are returned, even though gollum thinks there were 0 matches (the `0` in parenthesis next to the page title). A complete list of false positives can be seen below:

![image](https://cloud.githubusercontent.com/assets/794251/7011850/93c5726a-dc7a-11e4-9445-2e754d213e6f.png)

**Comment by dometto** [comment]
@techwiz24 this should be fixed in `HEAD`

**Comment by techwiz24** [comment]
@dometto Seems to be the case, thanks! Any idea when the next version will be cut?
