### ISSUE TITLE
conflict gitlab-grit(mime-types ~> 1.15) and gollum-rugged_adapter(mime-types ~> 2.6)

### ISSUE THREAD

**Issue by rgroux** [gollum/rugged_adapter#9]
I Can't upgrade the gem because `gitlab-grit` require `mime-types ~> 1.15`, so i am stuck into `gollum-rugged_adapter 0.3b`.

`mime-type ~>2.6` is mandatory? anyway i did a gitlab-grit [PR](https://github.com/gitlabhq/grit/pull/53) to use a newer `mime-type` gem.

I am not sure the gitlab-grit will be upgraded because last commit/merge is very old

Thanks
/Richard

**Comment by dometto** [comment]
Ah, that's an annoying one. As long as the git-adapter is still default 
in gollum I guess we'll have this problem. We could fallback to 
mime-types 1.15 for this adapter, but that seems weird. As a workaround 
you can just manually remove the git-adapter dependency from 
gollum-lib's gemspec (but of course that won't work when `gem 
install`'ing gollum).

**Comment by bartkamphorst** [comment]
I don't think we necessarily have to fall back to mime-types 1.15 specifically; couldn't we just be more lenient in our definition of this dependency in our gemspec?

**Comment by dometto** [comment]
On 27-07-15 17:42, Bart Kamphorst wrote:
>
> I don't think we necessarily have to fall back to mime-types 1.15 
> specifically; couldn't we just be more lenient in our definition of 
> this dependency in our gemspec?
>
:+1:

**Comment by rgroux** [comment]
@bartkamphorst , @dometto 

great,

The [PR](https://github.com/gitlabhq/grit/pull/53) i made for `gitlab-grit` was merged, not yet into rebygem repo.

Anyway it must be good to be lenient in the definition of the mime-types dependencies.

Thanks 4 all
/Richard

**Comment by dometto** [comment]
@damianesteban iin https://github.com/gollum/gollum/issues/1057 is also reporting conflicts with `mime-types`. Can we safely just leave out the version requirement from the gemspec?

**Comment by bartkamphorst** [comment]
We could, I suppose, but the other option is to specify 1.15 or later: `>= 1.15`.

**Comment by dometto** [comment]
Both the adapter specs and the gollum-lib tests are passing when using mime-types 1.15, so I'm changing it to `>= 1.15` indeed.

**Comment by dometto** [comment]
Fixed in release 0.4.1. Sorry for the wait.
